### ISSUE TITLE
Examples for VMware REST modules

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#114]
##### SUMMARY

Hello,
There is no working example for this module.

I've been told this is a replacement for httpapi
Is this a new connection type ?, if so a working usage example would be appreciated.

Rob

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by Akasurde** [comment]
@RobVerduijn The modules in this repo are based upon the REST interface and do not use HTTP API connection plugin. 

You can install collection as 

```
$ ansible-galaxy collection install vmware.vmware_rest
```

Now, you can start using this collection. Here is an example of getting information about datacenter id.

```yaml
cat get_vcenter_info.yml
---
- hosts: localhost
  tasks:
    - name: Get My vCenter
      vmware.vmware_rest.vcenter_datacenter_info:
        vcenter_username: administrator@vsphere.local
        vcenter_password: Esxi@123$%
        vcenter_hostname: 10.65.201.177
      register: r

    - set_fact:
        datacenter_id: "{{ (r.value | selectattr('name', 'equalto', 'Asia-Datacenter1') | map(attribute='datacenter'))[0] }}"

    - debug:
        msg: "{{ datacenter_id }}"
```
