### ISSUE TITLE
modules to work with templates

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#148]
##### SUMMARY

There currently are no modules to work with templates 
- create a vm from a template
- create a template from a vm

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by brandon-tharp** [comment]
Any idea on a timeline for this?  I am new to ansible and wanted to use vmware.vmware_rest collection to replace a bash script.  I based my current work with vmware_rest on the Ansible Fest 2020 talk "manage your guest VMs with REST based modules for VMware vSphere", which enables me to create a VM, but not clone from a template.  I guess I will have to use the old method of pyvmomi and come back to this later.

**Comment by Akasurde** [comment]
@brandon-tharp Thanks for requesting. You can create a basic VM from a template like the following - 

```yaml
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vcenter_vars.yml
  vars:
    cluster_name: 'Asia-Cluster1'
    datastore_name: 'ds_200'
    folder_name: 'prod'
    vm_name: CentOS7_Rest_2
  tasks:
    - name: Get virtual machine info
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        filter_names:
        - "{{ vm_name }}"
        vcenter_validate_certs: False
      register: vm_info

    - name: Get Cluster info
      vmware.vmware_rest.vcenter_cluster_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        filter_names:
        - "{{ cluster_name }}"
        vcenter_validate_certs: False
      register: cluster_info

    - name: Get Resource info for {{ cluster_name }}
      vmware.vmware_rest.vcenter_cluster_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        cluster: "{{ cluster_info.value[0].cluster }}"
      register: resource_pool_info

    - name: Get datastore info
      vmware.vmware_rest.vcenter_datastore_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        filter_names:
        - "{{ datastore_name }}"
      register: datastore_info

    - name: Get folder info
      vmware.vmware_rest.vcenter_folder_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        filter_names:
        - '{{ folder_name }}'
      register: folder_info

    - set_fact:
        source_vm_id: "{{ vm_info.value[0].vm }}"
        cluster_id: '{{ cluster_info.value[0].cluster }}'
        datastore_id: '{{ datastore_info.value[0].datastore }}'
        folder_id: '{{ folder_info.value[0].folder }}'
        resource_pool_id: '{{ resource_pool_info.value.resource_pool }}'
        network_id: '{{ network_info.value[0].network }}'

    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        placement:
          cluster: '{{ cluster_id }}'
          datastore: '{{ datastore_id }}'
          folder: '{{ folder_id }}'
          resource_pool: '{{ resource_pool_id }}'
        name: "{{ vm_name }}"
        source: "{{ source_vm_id }}"
        guest_OS: OTHER_LINUX_64
```

I am in process of adding new scenario guide here - https://docs.ansible.com/ansible/devel/scenario_guides/guide_vmware_rest.html

Please contribute your own scenarios here so that we can onboard as many people as possible.

**Comment by RobVerduijn** [comment]
Isn't that a clone of a vm ? 
or can you simply specify a template where you use the source_vm_id ?

Rob

**Comment by Akasurde** [comment]
Yes, this is a clone from VM since vCenter does not provide API to find MOID of template - https://github.com/ansible-collections/vmware.vmware_rest/issues/165.

But with the help of the `vmware_guest_info` module from `community.vmware` collection, you can achieve this - 

```yaml
  - name: Gather Managed object ID (moid) from a template using the vSphere API output schema for REST Calls
    community.vmware.vmware_guest_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ template_name }}"
      schema: "vsphere"
      properties:
        - _moId
    delegate_to: localhost
    register: moid_info

  - set_fact:
      template_moid: "{{ moid_info.instance.moid }}"
```
