### ISSUE TITLE
Unable to import vmware.vmware_rest.vcenter_vm_info due to invalid syntax

### ISSUE THREAD

**Issue by ehm-wehb** [ansible-collections/vmware.vmware_rest#151]
I initially mentioned this issue on IRC and was asked to formally file it here. 

##### SUMMARY
Attempting to gather basic vm_info to begin testing the Vmware rest modules.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware.vmware_rest.vcenter_vm_info

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mwebb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]

##### CONFIGURATION

```
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04.5 LTS via WSL on Windows server 2019

##### STEPS TO REPRODUCE

Ran "ansible-galaxy collection install vmware.vmware_rest"
Wrote test playbook below
Executed playbook with ansible-playbook -i hosts get_vmtest.yml
Received the error: Unable to import vmware.vmware_rest.vcenter_vm_info due to invalid syntax
Also installed python3-aiohttp at the advise of Goneri

```yaml


        ---
        - hosts: all
          gather_facts: false
          connection: local
          vars:
            ansible_python_interpreter: /usr/bin/python3
          vars_files:
            - vcenter_vars.yml
          vars_prompt:
            - name: vcenter_password
              prompt: "Please enter vcenter password"
              private: yes    
          tasks:
             - name: Get VM Info
               vmware.vmware_rest.vcenter_vm_info:
                 vcenter_username: "{{ vcenter_username }}"
                 vcenter_password: "{{ vcenter_password }}"
                 vcenter_hostname: "{{ vcenter_hostname }}"
                 vcenter_validate_certs: no
               register: vm_info
               delegate_to: localhost
```

##### EXPECTED RESULTS
I was expecting to get some vm_info :)

##### ACTUAL RESULTS

```
ansible-playbook -i hosts get-vmtest.yml -vvvv
ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mwebb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/mwebb/Git/Ansible/vmware/hosts as it did not pass its verify_file() method
script declined parsing /home/mwebb/Git/Ansible/vmware/hosts as it did not pass its verify_file() method
auto declined parsing /home/mwebb/Git/Ansible/vmware/hosts as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /home/mwebb/Git/Ansible/vmware/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: get-vmtest.yml ***********************************************************************************************
Positional arguments: get-vmtest.yml
remote_user: root
become_method: sudo
inventory: (u'/home/mwebb/Git/Ansible/vmware/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in get-vmtest.yml
Read vars_file 'vcenter_vars.yml'
Please enter vcenter password:
Read vars_file 'vcenter_vars.yml'
Read vars_file 'vcenter_vars.yml'

PLAY [all] *************************************************************************************************************
META: ran handlers
Read vars_file 'vcenter_vars.yml'
Read vars_file 'vcenter_vars.yml'

TASK [Get VM Info] *****************************************************************************************************
task path: /home/mwebb/Git/Ansible/vmware/get-vmtest.yml:21
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: mwebb
<localhost> EXEC /bin/sh -c 'echo ~mwebb && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mwebb/.ansible/tmp `"&& mkdir "` echo /home/mwebb/.ansible/tmp/ansible-tmp-1602698642.59-1739-29260445887749 `" && echo ansible-tmp-1602698642.59-1739-29260445887749="` echo /home/mwebb/.ansible/tmp/ansible-tmp-1602698642.59-1739-29260445887749 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/mwebb/.ansible/tmp/ansible-tmp-1602698642.59-1739-29260445887749/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "msg": "Unable to import vmware.vmware_rest.vcenter_vm_info due to invalid syntax"
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
