### ISSUE TITLE
Unable to create CentOS vm using vcenter_vm

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/vmware.vmware_rest#158]
##### SUMMARY
I am unable to create CentOS 7 VM using vcenter_vm with following yaml

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vcenter_vm

##### ANSIBLE VERSION

```paste below
2.11 devel
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vcenter_vars.yml
  vars:
    cluster_name: 'Asia-Cluster1'
    datastore_name: 'ds_200'
    folder_name: 'prod'
    vm_name: CentOS7_Rest
  tasks:
    - name: Get Cluster info
      vmware.vmware_rest.vcenter_cluster_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        filter_names:
        - "{{ cluster_name }}"
        vcenter_validate_certs: False
      register: cluster_info

    - name: Get Resource info for {{ cluster_name }}
      vmware.vmware_rest.vcenter_cluster_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        cluster: "{{ cluster_info.value[0].cluster }}"
      register: resource_pool_info

    - name: Get datastore info
      vmware.vmware_rest.vcenter_datastore_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        filter_names:
        - "{{ datastore_name }}"
      register: datastore_info

    - name: Get folder info
      vmware.vmware_rest.vcenter_folder_info:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        filter_names:
        - '{{ folder_name }}'
      register: folder_info

    - debug:
        msg: "{{ cluster_info.value[0].cluster }} {{ datastore_info.value[0].datastore }} {{ folder_info.value[0].folder }} {{ resource_pool_info.value.resource_pool }}"

    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_validate_certs: False
        placement:
          cluster: '{{ cluster_info.value[0].cluster }}'
          datastore: '{{ datastore_info.value[0].datastore }}'
          folder: '{{ folder_info.value[0].folder }}'
          resource_pool: '{{ resource_pool_info.value.resource_pool }}'
        name: "{{ vm_name }}"
        guest_OS: CENTOS_7_64
        hardware_version: VMX_12
        state: present
        boot:
          type: BIOS
        memory:
          hot_add_enabled: true
          size_MiB: 2048
        # disks:
        #   - new_vmdk:
        #       capacity: 50000000000
        cdroms:
          - backing:
              # device_access_type: EMULATION
              iso_file: "[ds_171_2] isos/CentOS-7.0-1406-x86_64-DVD.iso"
              type: ISO_FILE
          - backing:
              # device_access_type: EMULATION
              iso_file: "[ds_200] iso/kickstart_config.iso"
              type: ISO_FILE


```

##### EXPECTED RESULTS

VM should be created

##### ACTUAL RESULTS

```paste below
TASK [Create a VM] ****************************************************************************
task path: /Volumes/data/src/playbooks/vmware/REST/create_vm.yml:54
fatal: [localhost]: FAILED! => {"_debug_info": {"operation": "create", "status": 400}, "changed": false, "type": "com.vmware.vapi.std.errors.unsupported", "value": {"messages": [{"args": ["CENTOS_7_64"], "default_message": "Unable to get recommended disk size for the guest OS. Guest OS 'CENTOS_7_64' is not supported.", "id": "com.vmware.api.vcenter.vm.device.disk.unsupported_gos_get_disk_size"}]}}
```
