### ISSUE TITLE
Unable to find template using vcenter_vm_info

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/vmware.vmware_rest#165]
##### SUMMARY
I have a VM template and if I want to get moid using `vcenter_vm_info` module. The module returns nothing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vcenter_vm_info

##### ANSIBLE VERSION

```paste below
Ansible 2.11 devel
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - name: Get VM template
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
          - xd
      register: r

    - debug:
        msg: "{{ r.value[0].vm }}"
```

##### ACTUAL RESULTS

should return information about the vm template or add a note in as a caveat.

```paste below
TASK [Get VM template] *********************************************************************************
task path: /Volumes/data/src/playbooks/vmware/REST/get_vm.yml:4
ok: [localhost] => {"_debug_info": {"operation": "get", "status": 200}, "changed": false, "value": []}

TASK [debug] **********************************************************************************
task path: /Volumes/data/src/playbooks/vmware/REST/get_vm.yml:14
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/Volumes/data/src/playbooks/vmware/REST/get_vm.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug:\n      ^ here\n"}
```
