### ISSUE TITLE
vcenter_vm fails on vCenter 7.0.1

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/vmware.vmware_rest#176]
##### SUMMARY
vcenter_vm fails to create vm using following task on vCenter 7.0.1 version

```yaml
    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        placement:
          datastore: '{{ datastore_id }}'
          folder: '{{ folder_id }}'
          resource_pool: '{{ resource_pool_id }}'
        name: test_vm1
        guest_OS: DEBIAN_8_64
        hardware_version: VMX_11
        memory:
          hot_add_enabled: true
          size_MiB: 1024
      register: _result
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vcenter_vm

##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below
vcenter 7.0.1
```

##### OS / ENVIRONMENT
MacOS

##### STEPS TO REPRODUCE
As per above

##### EXPECTED RESULTS
VM should get created.

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"_debug_info": {"operation": "create", "status": 400}, "changed": false, "type": "com.vmware.vapi.std.errors.invalid_argument", "value": {"error_type": "INVALID_ARGUMENT", "messages": []}}
```

**Comment by goneri** [comment]
Hi @Akasurde, Can you still reproduce the problem?

**Comment by Akasurde** [comment]
With above playbook I can reproduce this issue.

I found that following playbooks works for me - 

```yaml
    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        boot:
          delay: 0
          enter_setup_mode: false
          retry: false
          retry_delay: 10000
          type: "BIOS"
        boot_devices: []
        cdroms:
          - allow_guest_control: true
            backing:
              type: "ISO_FILE"
              iso_file: "[ds_200] iso/rhel_8.3_ks.iso"
            ide:
              master: true
              primary: true
            label: "CD/DVD drive 1"
            start_connected: true
            type: "IDE"
        cpu:
          cores_per_socket: 1
          count: 1
          hot_add_enabled: false
          hot_remove_enabled: false
        disks:
          - new_vmdk:
              capacity: 536870912
            label: "Hard disk 1"
            scsi:
              bus: 0
              unit: 0
            type: "SCSI"
        guest_OS: "OTHER_LINUX_64"
        hardware_version: "VMX_13"
        memory:
          hot_add_enabled: true
          size_MiB: 2048
        name: test_vm_3
        nics:
          - start_connected: true
            type: VMXNET3
            mac_type: GENERATED
            backing:
                type: STANDARD_PORTGROUP
                network: "{{ network_id }}"
        scsi_adapters:
          - label: "SCSI controller 0"
            scsi:
              bus: 0
              unit: 7
            sharing: "NONE"
            type: "PVSCSI"
        placement:
          datastore: '{{ datastore_id }}'
          folder: '{{ folder_id }}'
          resource_pool: '{{ resource_pool_id }}'
      register: _result
```
