### ISSUE TITLE
vcenter_vm_storage_policy module throws <class 'dict'> cannot be converted to a list

### ISSUE THREAD

**Issue by alinabuzachis** [ansible-collections/vmware.vmware_rest#190]
##### SUMMARY

vcenter_vm_storage_policy throws
```
TASK [vcenter_vm_scenario1 : Adjust VM storage policy] **************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument disks is of type <class 'dict'> and we were unable to convert to list: <class 'dict'> cannot be converted to a list"}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vcenter_vm_storage_policy

##### STEPS TO REPRODUCE

```yaml
- name: Prepare the disk policy dict
  set_fact:
    vm_disk_policy: "{{ {} | combine({ my_new_disk.id: {'policy': my_storage_policy.policy, 'type': 'USE_SPECIFIED_POLICY'} }) }}"

- name: Adjust VM storage policy
  vmware.vmware_rest.vcenter_vm_storage_policy:
    vm: '{{ test_vm1_info.id }}'
    vm_home:
      type: USE_DEFAULT_POLICY
    disks: '{{ vm_disk_policy }}'
  register: _result
```

**Comment by MallocArray** [comment]
This is how I'm successfully using this module to assign a policy:

```yaml

    - name: Gather VM Information
      community.vmware.vmware_guest_disk_info:
        hostname: "{{ vcenter }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs | default('no') }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ computername }}"
      register: vm_info


    - name: Prepare the disk policy for each disk
      # Need a dictionary of every disk and the policy for each disk
      # Combining into one list with every disk and the same policy on each disk
      set_fact:
        vm_disk_policy: "{{ vm_disk_policy | default([]) + [{ 'unit_number': item.value.unit_number, 'policy': vcenter_storage_policy }] }}"
      loop: "{{ vm_info.guest_disk_info | dict2items }}"
      loop_control:
        label: "{{ item.value.label }} {{ item.value.backing_filename }}"


    - name: Assign Storage Policy to VM and all disks
      # Assigns a VM Storage Policy to all disks and the VM Home folder
      # If there are no other disks, the option for "Configure per disk" is disabled and future disk adds will use the same policy using GUI
      # Ansible disk additions do not appear to use the current policy
      community.vmware.vmware_guest_storage_policy:
        hostname: "{{ vcenter }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs | default('no') }}"
        name: "{{ computername }}"
        disk: "{{ vm_disk_policy }}"
        vm_home: "{{ vcenter_storage_policy }}"
      delegate_to: localhost
      register: policy_assignment
```
