### ISSUE TITLE
Create custom sized VMDK or multiple VMDKs at VM creation

### ISSUE THREAD

**Issue by latinofj-sei** [ansible-collections/vmware.vmware_rest#266]
##### SUMMARY
The current vcenter_vm module does not have the ability to create a custom sized VMDK at the time of VM creation.  I am able to create the 16GB default VMDK, but then I need to resize that VMDK later. 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware.vmware_rest.vcenter_vm

##### ADDITIONAL INFORMATION
 It would be extremely useful to be able to a custom sized VMDK1 and/or additional VMDKs at the time of creation, similar to existing functionality for CPU and memory and simalar to that found in the community.vmware.vmware_guest module.

```yaml
- name: Creating VM 
    vmware.vmware_rest.vcenter_vm:
      vcenter_hostname: "{{ vcenter_hostname }}"
      vcenter_password: "{{ vcenter_password }}"
      vcenter_username: "{{ vcenter_username }}"
      vcenter_validate_certs: false
      placement:
        cluster: "{{ newvm_cluster.value[0].cluster }}"
        datastore: "{{ newvm_datastore.value[0].datastore }}"
        folder: "group-v10000" 
      name: new-vm
      guest_OS: RHEL_8_64
      hardware_version: VMX_19
      cpu:
        count: 2
        cores_per_socket: 1
        hot_add_enabled: True
      memory:
        hot_add_enabled: true
        size_MiB: 2048
    register: _result
```

**Comment by goneri** [comment]
Hi @latinofj-sei,

You can actually already create a VM with a second disk and set a specific size:

```yaml
- name: Create a VM
  vmware.vmware_rest.vcenter_vm:
    placement:
      cluster: "{{ lookup('vmware.vmware_rest.cluster_moid', '/my_dc/host/my_cluster') }}"
      datastore: "{{ lookup('vmware.vmware_rest.datastore_moid', '/my_dc/datastore/local') }}"
      folder: "{{ lookup('vmware.vmware_rest.folder_moid', '/my_dc/vm') }}"
      resource_pool: "{{ lookup('vmware.vmware_rest.resource_pool_moid', '/my_dc/host/my_cluster/Resources') }}"
    name: test_vm1
    guest_OS: RHEL_7_64
    hardware_version: VMX_11
    memory:
      hot_add_enabled: true
      size_MiB: 1024
    disks:
      - type: SATA
        backing:
          type: VMDK_FILE
          vmdk_file: "[local] test_vm1/{{ disk_name }}.vmdk"
      - type: SATA
        new_vmdk:
          name: second_disk
          capacity: 32000000000
    nics:
      - backing:
          type: STANDARD_PORTGROUP
          network: "{{ lookup('vmware.vmware_rest.network_moid', '/my_dc/network/VM Network') }}"
```
