### ISSUE TITLE
Add support for cloudinit userdata similar to community.vmware.vmware_guest/advanced_settings

### ISSUE THREAD

**Issue by MnrGreg** [ansible-collections/vmware.vmware_rest#310]
##### SUMMARY

vmware_rest does not provide the ability to set guestinfo.userdata. cloud-init userdata configuration therefor cannot be used.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- vmware.vmware_rest.vcenter_vm

##### ADDITIONAL INFORMATION
community.vmware version caters for this through 'advanced_settings':
https://github.com/ansible-collections/community.vmware/blob/main/docs/community.vmware.vmware_guest_module.rst#parameters

Example:
```yaml
  - name: Clone VM from template
    vmware.vmware_rest.vcenter_vm:
      advanced_settings:
        - key: guestinfo.metadata
          value: "{{ cloud_init_metadata }}"
        - key: guestinfo.metadata.encoding
          value:  base64
        - key: guestinfo.userdata
          value: "{{ cloud_init_userdata }}"
        - key: guestinfo.userdata.encoding
          value:  base64
```
