### ISSUE TITLE
Issue cloning a vm from a template using vcenter_vm module

### ISSUE THREAD

**Issue by lucas-benedito** [ansible-collections/vmware.vmware_rest#319]
##### SUMMARY
The documentation for vcenter_vm does not provide examples or a clear explanation of the expected data for the expected parameters when cloning a machine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module vcenter_vm

##### ANSIBLE VERSION
`2.12`

##### COLLECTION VERSION
```
2.1.4
```

##### STEPS TO REPRODUCE
Have a task using the vcenter_vm passing the necessary parameters.
```
    - name: Create a VM
      vmware.vmware_rest.vcenter_vm:
        state: clone 
        source: "{{ template_moid }}"
        placement:
          cluster: "{{ cluster_uid }}"
          datastore: "{{ datastore_uid }}"
          folder: "{{ folder_moid }}"
          datacenter: "{{ datacenter_uid }}"
        name: njcvesgrh7ts01
        memory:
          hot_add_enabled: true
          size_MiB: 2048
      register: _result
```

##### EXPECTED RESULTS
Task completed successfully.

##### ACTUAL RESULTS
```
TASK [Create a VM] ************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "value": {"error_type": "NOT_FOUND", "messages": [{"args": ["vm-123456:xxxxxxxx-xxxxx-xxxxx-xxxx-xxxxxxx"], "default_message": "Virtual machine with identifier 'xx-xxxxxxxx:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' does not exist.", "id": "com.vmware.api.vcenter.vm.not_found"}]}}
```

**Comment by Akasurde** [comment]
@lucas-benedito Thanks for reporting this issue. I see the `template_moid` is `"vm-123456:xxxxxxxx-xxxxx-xxxxx-xxxx-xxxxxxx"` whereas it should be something like this `vm-xxxxx`.

You can use - 

```yaml
- name: Get virtual machine info
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ vm_name }}"
      register: vm_info

    - debug:
        msg: "{{ vm_info.value[0].vm }}"
```

For getting respective VM information.
