### ISSUE TITLE
folder_moid_lookup not working consistently

### ISSUE THREAD

**Issue by robbevl** [ansible-collections/vmware.vmware_rest#324]
Sometimes, a folder 4 levels deep is not found, the lookup then returns an empty string.

Our folderstructure looks like this:
/DC/Applications/MYAPP/PRD

/DC/Applications/MYAPP is found, and MOID returned.
/DC/Applications/MYAPP/PRD is not found

If I create /DC/Applications/MYAPP/PROD it is found.
If that folder is then renamed to /DC/Applications/MYAPP/PRD the plug can't find it any more.

I'm not sure what the issue is:
- It's not the all caps, because it can find /DC/Applications/MYAPP/TESTING
- It's not three letter named, cause it can find /DC/Applications/MYAPP/RND
- It's not even PRD and TST being "special" because it can find /DC/Applications/MYAPP2/PRD. Then again, /DC/Applications/MYAPP2/PROD couldn't be found

It looks totally random, but it's always four levels deep, and once it decides it can't find a name it will _never_ find that name, not even if you delete and recreate the folder, or if you rename a folder that can be found.

Note that [vmware.vmware_rest.vcenter_folder_info](https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.vcenter_folder_info_module.rst) _can_ find those problematic folders.

If someone can help me pinpoint this I'm all ears.
I'll use a workaround like this for now:

```
- name: Get folder
  vmware.vmware_rest.vcenter_folder_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    filter_names:
      - "{{ deploy_folder | basename }}"
    parent_folders:
      - "{{ lookup('vmware.vmware_rest.folder_moid', deploy_folder | dirname) }}"
  register: my_folder
```

`"{{ my_folder.value[0].folder }}"` 
gives me then the same value as I expected from
` "{{ lookup('vmware.vmware_rest.folder_moid', deploy_folder) }}"`

**Comment by robbevl** [comment]
While the workaround is working, I noticed that other lookups have the same issue..
I have no choice but convert our deployscript to community.vmware :(

**Comment by goneri** [comment]
Thank you @robbevl for the bug report. What version of vSphere do you use?

**Comment by goneri** [comment]
I've tried to reproduce the problem with the following tasks:

```yaml
- name: Create the Applications folder
  community.vmware.vcenter_folder:
    datacenter_name: my_dc
    folder_name: Applications
    folder_type: vm
    state: present
- name: Create the MYAPP folder
  community.vmware.vcenter_folder:
    datacenter_name: my_dc
    folder_name: MYAPP
    folder_type: vm
    parent_folder: Applications
    state: present
- include_tasks: create_delete.yaml
  with_sequence: start=0 end=400 stride=1
```

and this is the `create_delete.yaml`:

```yaml
- name: Create the PRD folder
  community.vmware.vcenter_folder:
    datacenter_name: my_dc
    folder_name: PRD
    folder_type: vm
    parent_folder: Applications/MYAPP
    state: present
- vcenter_folder_info:
  register: a
- debug: var=a
- set_fact:
    level1: "{{ lookup('vmware.vmware_rest.folder_moid', '/my_dc/vm/Applications') }}"
    level2: "{{ lookup('vmware.vmware_rest.folder_moid', '/my_dc/vm/Applications/MYAPP') }}"
    level3: "{{ lookup('vmware.vmware_rest.folder_moid', '/my_dc/vm/Applications/MYAPP/PRD') }}"

- debug:
    msg: "level1 {{ level1 }}, level2 {{ level2 }}, level3: {{ level3 }}"
- assert:
    that:
      - "level1 != ''"
      - "level2 != ''"
      - "level3 != ''"

- name: Delete the PRD folder
  community.vmware.vcenter_folder:
    datacenter_name: my_dc
    folder_name: PRD
    folder_type: vm
    parent_folder: Applications/MYAPP
    state: absen
```

This is not enough to reproduce the problem here (vSphere 7.0.3). Can you try on your side to confirm this is enough to trigger the error.

**Comment by robbevl** [comment]
Hi, thanks for taking the time to look into this!
We're on vSphere 7.0.3.00300.

I adapted the tasks slightly (needed to provide custom vcenter_hostname and user, also provided our actual dc name), but it did fail on the first iteration:

```
TASK [set_fact] ********************************************************************************************************
ok: [localhost]

TASK [debug] ***********************************************************************************************************
ok: [localhost] =>
  msg: 'level1 group-v2003, level2 group-v21760, level3: '

TASK [assert] **********************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  assertion: level3 != ''
  evaluated_to: false
  msg: Assertion failed
```


Here's the literal playbook I used (minus vsphere login info).

test_moid.yml:

```
---


- name: Test folder MOID
  hosts: localhost
  gather_facts: False
  vars:
    vcenter_hostname: <removed>
    vcenter_username: <removed>
    vcenter_password: <removed>
  tasks:

    - name: Create the Applications folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter_name: NLDTC1
        folder_name: Applications
        folder_type: vm
        state: present

    - name: Create the MYAPP folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter_name: NLDTC1
        folder_name: MYAPP
        folder_type: vm
        parent_folder: Applications
        state: present

    - include_tasks: test_create_delete.yml
      with_sequence: start=0 end=400 stride=1

```


test_create_delete.yml:

```
---

- name: Create the PRD folder
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter_name: NLDTC1
    folder_name: PRD
    folder_type: vm
    parent_folder: Applications/MYAPP
    state: present
- vmware.vmware_rest.vcenter_folder_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
  register: a
- debug: var=a
- set_fact:
    level1: "{{ lookup('vmware.vmware_rest.folder_moid', '/NLDTC1/Applications', vcenter_hostname=vcenter_hostname, vcenter_username=vcenter_username, vcenter_password=vcenter_password) }}"
    level2: "{{ lookup('vmware.vmware_rest.folder_moid', '/NLDTC1/Applications/MYAPP', vcenter_hostname=vcenter_hostname, vcenter_username=vcenter_username, vcenter_password=vcenter_password) }}"
    level3: "{{ lookup('vmware.vmware_rest.folder_moid', '/NLDTC1/Applications/MYAPP/PRD', vcenter_hostname=vcenter_hostname, vcenter_username=vcenter_username, vcenter_password=vcenter_password) }}"

- debug:
    msg: "level1 {{ level1 }}, level2 {{ level2 }}, level3: {{ level3 }}"
- assert:
    that:
      - "level1 != ''"
      - "level2 != ''"
      - "level3 != ''"

- name: Delete the PRD folder
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter_name: NLDTC1
    folder_name: PRD
    folder_type: vm
    parent_folder: Applications/MYAPP
    state: absent
```

Only actual difference I can see with what you did is the dc name (not sure it is relevant).
Also, you added a "vm" folder in your lookup : /my_dc/vm/Applications.
