### ISSUE TITLE
Filter_names not working as expected in vmware.vmware_rest.vcenter_network_info

### ISSUE THREAD

**Issue by rit001** [ansible-collections/vmware.vmware_rest#354]
##### SUMMARY
Filter_names not working as expected in vmware.vmware_rest.vcenter_network_info

##### ISSUE TYPE
An unfiltered call to vmware.vmware_rest.vcenter_network_info returns the following

`ok: [localhost] => {
    "network1_info": {
        "changed": false,
        "failed": false,
        "value": [
            {
                "name": "VM Network",
                "network": "network-3160",
                "type": "STANDARD_PORTGROUP"
            },
            {
                "name": "VM Network Private",
                "network": "network-3161",
                "type": "STANDARD_PORTGROUP"
            },
            {
                "name": "VM Network Public",
                "network": "network-3162",
                "type": "STANDARD_PORTGROUP"
            }
        ]
    }
}
`
 If I use the following

`    - name: Get a list of the networks with a filter
      vmware.vmware_rest.vcenter_network_info:
        names:
          - "VM Network Public" 
      register: network2_info

    - debug:
        var: network2_info
`

returns an empty list, rather than a list with a single entry.

##### COMPONENT NAME
vmware.vmware_rest.vcenter_network_info

##### ANSIBLE VERSION

```
nsible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]

```

##### COLLECTION VERSION

```paste below
vmware.vmware_rest 2.2.0 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: Get a list of the networks with a filter
      vmware.vmware_rest.vcenter_network_info:
#        filter_types: STANDARD_PORTGROUP
        names:
          - "VM Network Public" 
      register: network2_info

    - debug:
        var: network2_info
```

##### EXPECTED RESULTS
The returned list should have contained an entry that matched "VM Network Public", instead, it returned an empty list

##### ACTUAL RESULTS

```paste below

```
