### ISSUE TITLE
Is there a similar module in vmware_rest collection for vmware_host_firewall_manager?

### ISSUE THREAD

**Issue by sayantandas** [ansible-collections/vmware.vmware_rest#358]
##### SUMMARY

Looking for a similar module in vmware_rest for vmware_host_firewall_manager

##### ISSUE TYPE
-  similar module in vmware_rest for vmware_host_firewall_manager

##### COMPONENT NAME

 vmware_host_firewall_manager

##### ADDITIONAL INFORMATION

I'm looking for a vmware_rest module which can perform the following

- Manage multiple rule set for an ESXi Host
- Enable vvold rule set for all ESXi Host in given Cluster
- Manage IP and network based firewall permissions for ESXi

I have seen  vmware_rest.appliance_networking_firewall_inbound_module but this module doesn't do much

```
- name: Manage IP and network based firewall permissions for ESXi
  community.vmware.vmware_host_firewall_manager:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    esxi_hostname: '{{ esxi_hostname }}'
    rules:
        - name: gdbserver
          enabled: True
          allowed_hosts:
            all_ip: False
            ip_address:
              - 192.168.20.10
              - 192.168.20.11
        - name: CIMHttpServer
          enabled: True
          allowed_hosts:
            all_ip: False
            ip_network:
              - 192.168.100.0/24
        - name: remoteSerialPort
          enabled: True
          allowed_hosts:
            all_ip: False
            ip_address:
              - 192.168.100.11
            ip_network:
              - 192.168.200.0/24
  delegate_to: localhost
```
