### ISSUE TITLE
Ability to define group module_defaults

### ISSUE THREAD

**Issue by jeichler** [ansible-collections/vmware.vmware_rest#361]
##### SUMMARY
Allow to specify module_defaults by defining action_groups in `meta/runtime.yml`
Doc reference: https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html#module-defaults-groups

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Collection

##### ADDITIONAL INFORMATION

When currently using the collection, for each module you specify module parameters such as `vcenter_username`, `vcenter_password`, `vcenter_hostname`. This clutters the automation code. It'd be easier to be able to use module defaults for the entire group since specifying them for each module individually becomes also a rather lengthy list.

```yaml
- name: Dummy
  hosts: localhost
  connection: local
  gather_facts: false
  module_defaults:
    group/vmware.vmware_rest.vmware_rest:
      vcenter_hostname: "{{ vmware_host }}"
      vcenter_username: "{{ vmware_user }}"
      vcenter_password: "{{ vmware_password }}"
      vcenter_validate_certs: "{{ vmware_validate_certs }}"
```

with the following specified (local modification of the collection) in `meta/runtime.yml` in the collection:

```yaml
[...]
action_groups:
  vmware_rest:
    - vcenter_datastore_info
    - ...
    - ...
```
The `group/vmware` module default points to the community.vmware modules, a similar comfort is at the end the desired behaviour :)
