### ISSUE TITLE
filter_names does not document or gracefully handle spaces

### ISSUE THREAD

**Issue by jeffcpullen** [ansible-collections/vmware.vmware_rest#362]
##### SUMMARY

The _info modules provide a method of filtering names but will fail on names that contain a space. If the module does not gracefully handle names with spaces it should at least be documented how names should be written to be tolerated by the modules. Adding a '%20' in place of a space seems to make the module function as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware.vmware_rest.vcenter_datacenter_info

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.12.3]
  config file = /Users/jpullen/.ansible.cfg
  configured module search path = ['/Users/jpullen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jpullen/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:28:31) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
vmware.vmware_rest 2.2.0 
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/jpullen/.ansible.cfg) = ['/Users/jpullen/inventory/hosts']
HOST_KEY_CHECKING(/Users/jpullen/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
vars:
  vcenter_config_datacenter: "Homelab DC"
tasks:
- name: List datacenters
  vmware.vmware_rest.vcenter_datacenter_info:
    filter_names:
      # fails to return any results
      - "{{ vcenter_config_datacenter }}"
      # Replace blank spaces with %20 to make this work (shown in line below)
      # - "{{ vcenter_config_datacenter | replace(' ', '%20') }}"
  register: my_datacenters

- name: Debug datacenter info
  ansible.builtin.debug:
    var: my_datacenters
```

##### EXPECTED RESULTS

```
TASK [create_vsphere_vm : Debug datacenter info] *******************************************
ok: [localhost] => {
    "my_datacenters": {
        "changed": false,
        "failed": false,
        "value": [
            {
                "datacenter": "datacenter-3",
                "name": "Homelab DC"
            }
        ]
    }
}
```
##### ACTUAL RESULTS

If the user leaves any values without spaces using a _info module it will fail to filter. Quotes and backslashes will not work. Only adding the '%20' to the variables will result in the expected results.

```paste below
TASK [create_vsphere_vm : Debug datacenter info] *******************************************
ok: [localhost] => {
    "my_datacenters": {
        "changed": false,
        "failed": false,
        "value": []
    }
}
```
