### ISSUE TITLE
appliance_vmon_service with both state and startup_type does not do both

### ISSUE THREAD

**Issue by MallocArray** [ansible-collections/vmware.vmware_rest#365]
##### SUMMARY

Attempting to use module to configure a service that is Stopped and Manual to `state: start` and `startup_type AUTOMATIC`.  If both are defined in the same task,, then the state becomes started, but startup_type is not modified and task returns OK on subsequent runs

Edit: It also appear that if only State is defined, it will start/stop, but it may not reflect a changed status properly. In a further test, changing `state: stop` resulted in a status of OK when it had been running and was changed to STOPPED in reality.  In this case, I had changed the service startup type to MANUAL in the task previous

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

appliance_vmon_service

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = /runner/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
vmware.vmware_rest 2.2.0 
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/runner/ansible.cfg) = ['/runner/collections']
DEFAULT_FILTER_PLUGIN_PATH(/runner/ansible.cfg) = ['/runner/custom_filters']
DEFAULT_ROLES_PATH(/runner/ansible.cfg) = ['/runner/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/runner/ansible.cfg) = ['/runner/custom_plugins/mitogen-0.3.0-rc.0/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(/runner/ansible.cfg) = 40
HOST_KEY_CHECKING(/runner/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/runner/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Execution Environment built with ansible-builder
vCenter 7.0 U3

##### STEPS TO REPRODUCE

```yaml
    - name: NetDumper Service configure automatic startup
      vmware.vmware_rest.appliance_vmon_service:
        vcenter_hostname: "{{ inventory_hostname }}"
        vcenter_username: "{{ vcenter_user }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vmware_validate_certs }}"
        service: netdumper
        startup_type: AUTOMATIC
        state: start
      delegate_to: localhost
      register: result
      until: result is not failed
      retries: 2
      delay: 60
```

##### EXPECTED RESULTS

Service will be both in a Started state and configured for Automatic startup

##### ACTUAL RESULTS

Task shows Changed, but using appliance_vmon_service_info we see that only state has changed to STARTED but startup_type is still MANUAL

Splitting into two separate tasks that modify one parameter at a time results in the desired outcome.

```paste below

```
