### ISSUE TITLE
appliance_vmon_service_info specifying a service still returns all

### ISSUE THREAD

**Issue by MallocArray** [ansible-collections/vmware.vmware_rest#366]
##### SUMMARY

When using appliance_vmon_service_info and specifying a service parameter, the registered output still shows all services and not only the specified service

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
appliance_networking_noproxy

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = /runner/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
vmware.vmware_rest 2.2.0 
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/runner/ansible.cfg) = ['/runner/collections']
DEFAULT_FILTER_PLUGIN_PATH(/runner/ansible.cfg) = ['/runner/custom_filters']
DEFAULT_ROLES_PATH(/runner/ansible.cfg) = ['/runner/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/runner/ansible.cfg) = ['/runner/custom_plugins/mitogen-0.3.0-rc.0/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(/runner/ansible.cfg) = 40
HOST_KEY_CHECKING(/runner/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/runner/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Execution Environment built with ansible-builder
vCenter 7.0 U3

##### STEPS TO REPRODUCE

```yaml
    - name: NetDumper Service Info
      # https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.appliance_networking_noproxy_module.rst
      vmware.vmware_rest.appliance_vmon_service_info:
        vcenter_hostname: "{{ inventory_hostname }}"
        vcenter_username: "{{ vcenter_user }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vmware_validate_certs }}"
        service: netdumper
      delegate_to: localhost
      register: result
      until: result is not failed
      retries: 2
      delay: 60
      tags:
        - netdumper
        - netdumper_info
```

##### EXPECTED RESULTS

Only information about the netdumper service will be displayed

##### ACTUAL RESULTS

Information about all known services are displayed. 

```paste below

```
