### ISSUE TITLE
vcenter_vm Advanced Options

### ISSUE THREAD

**Issue by vMarkusK** [ansible-collections/vmware.vmware_rest#367]
##### SUMMARY

Allow adding advanced options during VM Creation.

Allow adding advanced options for exiting VMs. Optional allow removing advanced options.

Similar property of the vmware_guest community module: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-advanced_settings

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vcenter_vm

##### ADDITIONAL INFORMATION

Example for a dedicated module:
```yaml
---
- name: Lock the VM guest session when the remote console is disconnected
  community.vmware.vmware_guest_custom_attributes:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    uuid: "{{ item.uuid }}"
    state: present
    attributes:
      - name: "tools.guest.desktop.autolock"
        value: 'True'
  when: "'vCLS (' not in item.guest_name"
  with_items: "{{ vm_filtered }}"
```
