### ISSUE TITLE
vmware.vmware_rest.vcenter_ovf_libraryitem - Update existing template

### ISSUE THREAD

**Issue by sepetuks** [ansible-collections/vmware.vmware_rest#385]
##### SUMMARY

I am trying to update existing OVF template but it looks it is not updating it when I provide library_item_id.
All works ok when I need first OVF template to be cloned to library but I do not succed updateing Connten library template with new versions.
As per documentation"
`- library_item_id (str)`: Identifier of the library item that should be should be **updated**. (['present'])
https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.vcenter_ovf_libraryitem_module.rst
Per documentation I read it should be possible. So I either thats issue with documentation or with code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware.vmware_rest.vcenter_ovf_libraryitem

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/henris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/henris/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/henris/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/henris/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
vmware.vmware_rest 2.2.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

vCenter 7.0 Update 3j (20990077)

##### STEPS TO REPRODUCE

```yaml
    - name: Export the VM as an OVF on the library (new)
      vmware.vmware_rest.vcenter_ovf_libraryitem:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
        vcenter_rest_log_file: '/tmp/rest.log'
        session_timeout: 2900
        source:
          type: VirtualMachine
          id: '{{ vm1_info.id }}'
        target:
          library_id: '{{ library_id }}'
        create_spec:
          name: golden
          description: an OVF example
          flags: []
        state: present
      delegate_to: localhost  
      tags: library

   - name: Export the VM as an OVF on the library (update)
      vmware.vmware_rest.vcenter_ovf_libraryitem:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
        vcenter_rest_log_file: '/tmp/rest.log'
        session_timeout: 2900
        source:
          type: VirtualMachine
          id: '{{ vm1_info.id }}'
        target:
          library_id: '{{ library_id }}'
          library_item_id: '{{ library_item_id }}'
        create_spec:
          name: golden
          description: an OVF example2
          flags: []
        state: present
      delegate_to: localhost  
      tags: library
```

##### EXPECTED RESULTS

I would expect second task would do OVF template update, but task just finished without actions (no failure)

##### ACTUAL RESULTS

Second task is always giving status "ok" (I would expect **changed**)

```paste below
TASK [Export the VM as an OVF on the library (new)] ********************************************************************
changed: [Template -> localhost]

TASK [Export the VM as an OVF on the library (update)] *****************************************************************
ok: [Template -> localhost]
```
