### ISSUE TITLE
How to use a dict or loop for vcenter_vm_power.py?

### ISSUE THREAD

**Issue by Tronde** [ansible-collections/vmware.vmware_rest#409]
##### SUMMARY

The examples in [vcenter_vm_power.py](https://github.com/ansible-collections/vmware.vmware_rest/blob/main/plugins/modules/vcenter_vm_power.py) describes how to control the power status of one VM only.

It would be good to have an example explaining how to loop through a list or objects in some dict.

For example, when using following task:

```
- name: Creating VM(s)
  vmware.vmware_rest.vcenter_vm:
    vcenter_hostname: "{{ vmware_rest_provision_lab_vc }}"
    vcenter_username: "{{ vmware_rest_provision_lab_user }}"
    vcenter_password: "{{ vmware_rest_provision_lab_pass }}"
    vcenter_validate_certs: "{{ vmware_rest_provision_lab_validate_certs }}"
    placement:
      cluster: "{{ __resource_pool_info.id }}"
      datastore: "{{ __my_datastore.datastore }}"
      folder: "{{ __my_vm_folder.folder }}"
      resource_pool: "{{ __resource_pool_info.value.resource_pool }}"
    name: "{{ item.key }}"
    guest_OS: "{{ item.value.guest_OS }}"
    hardware_version: "{{ item.value.hardware_version }}"
    boot:
      type: BIOS
    cdroms:
      - allow_guest_control: true
        backing:
          type: "ISO_FILE"
          iso_file: "{{ vmware_rest_provision_lab_iso_path }}"
        label: "CD/DVD drive 1"
        start_connected: true
    cpu:
      count: "{{ item.value.cpu_count }}"
    memory:
      hot_add_enabled: "{{ item.value.hot_add_enabled }}"
      size_MiB: "{{ item.value.size_MiB }}"
    disks:
      - type: SCSI
        new_vmdk:
          name: "{{ item.key }}"
          capacity: "{{ item.value.disk_size }}"
          storage_policy:
            policy: "{{ item.value.storage_policy_spec }}"
    nics:
      - start_connected: true
        type: VMXNET3
        mac_type: GENERATED
        backing:
          type: STANDARD_PORTGROUP
          network: "{{ __my_network.network }}"
  with_dict: "{{ vmware_rest_provision_lab_guests }}"
  register: __result
```

This task creates several VMs that are specified in in `"{{ vmware_rest_provision_lab_guests }}"`. But I don't know how to power on all these VMs. How could this be done? Could you give an example, please?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

- [vcenter_vm_power.py](https://github.com/ansible-collections/vmware.vmware_rest/blob/main/plugins/modules/vcenter_vm_power.py)

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by alinabuzachis** [comment]
@Tronde Have you tried setting the state parameter https://github.com/ansible-collections/vmware.vmware_rest/blob/main/plugins/modules/vcenter_vm_power.py#L29?

**Comment by smatterchew** [comment]
@Tronde, if you register the results you should be able to use `json_query` to extract the `id` of each VM.  Use that list in a `loop:` to set the power state in another task.

**Comment by machacekondra** [comment]
@Tronde This is the way to do it.

```
- name: Start VMs
  vmware.vmware_rest.vcenter_vm_power:
    state: start
    vm: '{{ item.id }}'
  loop: "{{ __result.results }}"
```
