### ISSUE TITLE
Create cluster

### ISSUE THREAD

**Issue by lotaris-xx** [ansible-collections/vmware.vmware_rest#422]
##### SUMMARY
Allow for the creation of clusters

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins/modules/vcenter_cluster.py

##### ADDITIONAL INFORMATION
Creating clusters is a common activity that would be great to automate.

```yaml
- name: Create cluster in folder
  vmware.vmware_rest.vcenter_clusterr:
    datacenter: '{{ my_datacenter }}'
    folder: '{{ my_folder | default(omit)  }}' #If not given, use datastore default
    name: '{{ my_cluster_name }}'
```
