### ISSUE TITLE
"SSLCertVerificationError" when vcenter_validate_certs: false (Lookup Plugins)

### ISSUE THREAD

**Issue by alice-rc** [ansible-collections/vmware.vmware_rest#425]
##### SUMMARY

Returns "SSLCertVerificationError" when vcenter_validate_certs: false

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware.vmware_rest -> cloud.common

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /home/XXX/venv/custom/meta/ansible.cfg
  configured module search path = ['/home/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/XXX/venv/custom/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/XXX/venv/custom/collections
  executable location = /home/XXX/venv/custom/bin/ansible
  python version = 3.9.13 (main, Nov 16 2022, 15:11:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15.0.1)] (/home/XXX/venv/custom/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/XXX/venv/custom/collections/ansible_collections
Collection         Version
------------------ -------
vmware.vmware_rest 2.3.1 (tried 2.2.0 with the same result)
cloud.common       2.1.4
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/XXX/venv/custom/meta/ansible.cfg) = True
CALLBACKS_ENABLED(/home/XXX/venv/custom/meta/ansible.cfg) = ['ansible.posix.timer', 'ansible.posix.profile_tasks', 'ansible.posix>
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/home/XXX/venv/custom/collections']
COLOR_VERBOSE(/home/XXX/venv/custom/meta/ansible.cfg) = magenta
CONFIG_FILE() = /home/XXX/venv/custom/meta/ansible.cfg
DEFAULT_GATHERING(/home/XXX/venv/custom/meta/ansible.cfg) = smart
DEFAULT_TIMEOUT(/home/XXX/venv/custom/meta/ansible.cfg) = 30
DEPRECATION_WARNINGS(/home/XXX/venv/custom/meta/ansible.cfg) = False
DEVEL_WARNING(/home/XXX/venv/custom/meta/ansible.cfg) = False
GALAXY_SERVER_LIST(/home/XXX/venv/custom/meta/ansible.cfg) = ['public_galaxy']
HOST_KEY_CHECKING(/home/XXX/venv/custom/meta/ansible.cfg) = False
INTERPRETER_PYTHON(/home/XXX/venv/custom/meta/ansible.cfg) = auto_silent
LOCALHOST_WARNING(/home/XXX/venv/custom/meta/ansible.cfg) = False
USE_PERSISTENT_CONNECTIONS(/home/XXX/venv/custom/meta/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Oracle Linux Server 8.6

##### STEPS TO REPRODUCE

```yaml
- name: vcenter_facts | Ensure the deployment folder exists in vCenter
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    datacenter: "{{ datacenter }}"
    folder_name: OPS
    folder_type: vm
    state: present

- name: TEST
  ansible.builtin.debug:
    var: lookup('vmware.vmware_rest.folder_moid', '/REDACTED/vm/OPS', **connection_args)
  vars:
    connection_args:
      vcenter_hostname: "{{ vcenter_hostname }}"
      vcenter_username: "{{ vcenter_user }}"
      vcenter_password: "{{ vcenter_password }}"
      vcenter_validate_certs: false
```

##### EXPECTED RESULTS

Returns the MOID for the folder

##### ACTUAL RESULTS

```paste below
TASK [deploy_vm : vcenter_facts | Ensure the deployment folder exists in vCenter] ***
task path: /opt/dev/XXX/repo/active/awx_cac/roles/deploy_vm/tasks/vcenter_facts.yml:4
Wednesday 13 September 2023  08:18:36 -0700 (0:00:00.059)       0:00:05.044 ***
Wednesday 13 September 2023  08:18:36 -0700 (0:00:00.059)       0:00:05.043 ***
Using module file /home/XXX/venv/custom/collections/ansible_collections/community/vmware/plugins/modules/vcenter_folder.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: XXX
<localhost> EXEC /bin/sh -c '/home/XXX/venv/custom/bin/python3 && sleep 0'
ok: [REDACTED -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "REDACTED",
            "folder_name": "OPS",
            "folder_type": "vm",
            "hostname": "REDACTED",
            "parent_folder": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "state": "present",
            "username": "REDACTED",
            "validate_certs": false
        }
    },
    "result": {
        "msg": "Folder OPS already exists",
        "path": "/REDACTED/vm/OPS"
    }
}

TASK [deploy_vm : TEST] ********************************************************
task path: /opt/dev/XXX/repo/active/awx_cac/roles/deploy_vm/tasks/vcenter_facts.yml:24
Tuesday 12 September 2023  17:16:56 -0700 (0:00:00.060)       0:00:06.243 *****
Tuesday 12 September 2023  17:16:56 -0700 (0:00:00.060)       0:00:06.243 *****
exception during Jinja2 execution: Traceback (most recent call last):
  File "/home/XXX/venv/custom/lib64/python3.9/site-packages/ansible/template/__init__.py", line 831, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/home/XXX/venv/custom/collections/ansible_collections/cloud/common/plugins/plugin_utils/turbo/lookup.py", line 57, in run_on_daemon
    return self.execute(terms=terms, variables=variables, **kwargs)
  File "/home/XXX/venv/custom/collections/ansible_collections/cloud/common/plugins/plugin_utils/turbo/lookup.py", line 91, in execute
    raise EmbeddedModuleUnexpectedFailure(errors)
ansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: Unable to connect to vCenter or ESXi API at REDACTED: Authentication failure: Cannot connect to host REDACTED:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]
fatal: [REDACTED -> localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'vmware.vmware_rest.folder_moid'. Error was a <class 'ansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure'>, original message: Unable to connect to vCenter or ESXi API at REDACTED: Authentication failure: Cannot connect to host REDACTED:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]. Unable to connect to vCenter or ESXi API at REDACTED: Authentication failure: Cannot connect to host REDACTED:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]"
}
```
