### ISSUE TITLE
Add parameter to vmware.vmware_rest.appliance_networking_proxy that add proxy exceptions

### ISSUE THREAD

**Issue by mpsOxygen** [ansible-collections/vmware.vmware_rest#426]
##### SUMMARY

Add a parameter to the vmware.vmware_rest.appliance_networking_proxy module that adds dns names to the NO_PROXY option in the /etc/sysconfig/proxy file.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware.vmware_rest.appliance_networking_proxy

##### ADDITIONAL INFORMATION

Whan adding a proxy to the vCenter server it will use that proxy for all communication, including with the ESXi hosts. This causes problems at least with uploading OVAs tot he vCenter. See this KB: https://kb.vmware.com/s/article/81565
With the current parameters you need to add the proxy exceptions by hand, either thru the web interface https://vcenter.local:5480 or SSHing into the server and editing the /etc/sysconfig/proxy file and restarting services.

```yaml

```

**Comment by machacekondra** [comment]
You can set `noproxy` hosts with the `vmware.vmware_rest.appliance_networking_noproxy` module as follows:

```yaml
  - name: Set no proxy hosts
    vmware.vmware_rest.appliance_networking_noproxy:
      servers: "1.2.3.4,1.2.3.5"
      state: set
```
