### ISSUE TITLE
Unable to lookup vm_moid or vcenter_vm_info a VM Template not in Content Library

### ISSUE THREAD

**Issue by jeffmcutter** [ansible-collections/vmware.vmware_rest#473]
##### SUMMARY

Unable to lookup vmware.vmware_rest.vm_moid or vmware.vmware_rest.vcenter_vm_info a VM Template not in a content library.

Related to https://github.com/ansible-collections/vmware.vmware_rest/issues/453 unable to clone from a VM Template not in a content library.

I'm not sure that vm_moid and vcenter_vm_info should be the way to get it, but I don't see any equivalent for templates which are not in a content library.  template_moid and vcenter_template_info would be another option.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware.vmware_rest.vm_moid
vmware.vmware_rest.vcenter_vm_info

##### ADDITIONAL INFORMATION

```yaml
---
- name: Lookup test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Lookup a VM Template
      ansible.builtin.debug:
        msg: "{{ lookup('vmware.vmware_rest.vm_moid', '/Datacenter/templates/vmwrhel1_template') }}"

    - name: Get VM Template info
      vmware.vmware_rest.vcenter_vm_info:
        names:
          - vmwrhel1_template
      register: __template

    - name: Display template
      ansible.builtin.debug:
        var: __template

```
