### ISSUE TITLE
Unsupported property with name: library_id?library_id.

### ISSUE THREAD

**Issue by nikolatsi0** [ansible-collections/vmware.vmware_rest#478]
Dear all,

I have write this yaml. The idea behind is to create a VM from template, customize it and then convert the VM as a template again and save it to Content Libraby. A 3 months ago this was working, but now I receive an unusual error.

The yaml:

```
  - name: lookup MoID of Cluster
    ansible.builtin.debug: msg="Cluster {{ lookup('vmware.vmware_rest.cluster_moid', '/LAB/host/Lab01', **connection_args) }}"

  - name: lookup MoID of Folder
    ansible.builtin.debug: msg="Folder {{ lookup('vmware.vmware_rest.folder_moid', '/LAB/vm/GoldenGate', **connection_args) }}"

  - name: List all Local Content Library
    vmware.vmware_rest.content_locallibrary_info:
      vcenter_hostname: "{{ vcenter_server }}"
      vcenter_username: "{{ vcenter_user }}"
      vcenter_password: "{{ vcenter_pass }}"
      vcenter_validate_certs: False
    register: all_content_libraries
    delegate_to: localhost

  - name: Use the name to identify the right Content Library - Lab_iso
    set_fact:
      lab_lib: "{{ all_content_libraries.value | selectattr('name', 'equalto', 'Lab_iso')|first }}"
    delegate_to: localhost

  - name: Get the list of items of the HPLab_iso library
    vmware.vmware_rest.content_library_item_info:
      vcenter_hostname: "{{ vcenter_server }}"
      vcenter_username: "{{ vcenter_user }}"
      vcenter_password: "{{ vcenter_pass }}"
      vcenter_validate_certs: false    
      library_id: '{{ lab_lib.id }}'
    register: lib_items
```

The error:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "library_id": "07d17935-fafc-4fc3-8774-d5fd9d4159f8",
            "library_item_id": null,
            "session_timeout": null,
            "vcenter_hostname": "vcenter.bla.bla",
            "vcenter_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vcenter_rest_log_file": null,
            "vcenter_username": "automation",
            "vcenter_validate_certs": false
        }
    },
    "value": {
        "error_type": "INVALID_ARGUMENT",
        "messages": [
            {
                "args": [
                    "library_id?library_id"
                ],
                "default_message": "Unsupported property with name: library_id?library_id.",
                "id": "com.vmware.vapi.rest.unsupportedProperty"
            }
        ]
    }
}
```

Any ideas?
