### ISSUE TITLE
recursive_folder_or_rp_moid_search awaits objects_moid to be in order (but it isn't necessarily)

### ISSUE THREAD

**Issue by dbk-rabel** [ansible-collections/vmware.vmware_rest#500]
Hi.

We stumbled across this, because sometimes folder lookups worked fine and sometimes they didn't.

While troubleshooting we noticed that `recursive_folder_or_rp_moid_search` awaits `objects_moid` (which it gets from the API) to be in order of the path.
If they're not, https://github.com/ansible-collections/vmware.vmware_rest/blob/main/plugins/plugin_utils/lookup.py#L472 will never match.

But the API does not always send them in order.

We have a lookup that looks like this:

`lookup('vmware.vmware_rest.folder_moid', '/my_datacenter/my_topfolder/my_subfolder', **connection_args)`

In `get_all_objects_path_moid` there is an API call to a ressource like this:

https://<url>/api/vcenter/folder?datacenters=my_datacenter_moid&names=my_subfolder&names=my_topfolder

And it receives this from the API:

`[{'folder': 'my_subfolder_moid', 'name': 'my_subfolder', 'type': 'VIRTUAL_MACHINE'}, {'folder': 'my_topfolder_moid', 'name': 'my_top_folder', 'type': 'VIRTUAL_MACHINE'}]`

This only happens for folders that we've created in the last days. Not sure if this is the reason, why the API behaves like that.

But since the API is not consistent with the ordering, I think we can say that `recursive_folder_or_rp_moid_search` is broken right now.

Yours
  David

**Comment by dbk-rabel** [comment]
Could this maybe already have been fixed by #445 ?

**Comment by reusch** [comment]
Maybe this is also the same as #324

**Comment by mikemorency** [comment]
hi @dbk-rabel im having some trouble reproducing the issue. Im also experiencing the EmbeddedModuleUnexpectedFailure when I try to use these lookups.

Could you provide the version of the collection your using, the version of ansible packages (ansible and/or ansible-core), and your vcenter version? Also maybe a playbook to reproduce the issue?

I dont see any reason the playbook in 445 wouldnt work for you but other playbooks would, so thats interesting. If you have any insight into why that might be happening that would also be helpful

**Comment by dbk-rabel** [comment]
Hello @mikemorency .

We are using vmware.vmware_rest 3.0.1, ansible-core 2.15.11
vSphere Client version 8.0.2.00200

Here is an example playbook, but of course you would need to create the folders in vcenter first:

```yaml
---
- name: Test
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    directories:
      - folder/subfolder1
      - folder/subfolder2
  tasks:
    - name: Test
      ansible.builtin.debug:
        msg: "{{ item }} has MOID {{ lookup('vmware.vmware_rest.folder_moid', '/                                                                                                                                                             my_datacenter/' + item, **connection_args) }}"
      loop: "{{ directories }}"
```

As I said: It works if and only if the API returns the moids of the folders in the correct order. This is not guaranteed. We did not find out when or why it does so, but since it fails especially with newer folders, it might have something todo with the date when the folders where created.
