### ISSUE TITLE
vmon api service deprecated

### ISSUE THREAD

**Issue by MallocArray** [ansible-collections/vmware.vmware_rest#501]
##### SUMMARY
vCenter 8.0 U3 appears to have fully depreciated the API at /rest/appliance/vmon/service
https://knowledge.broadcom.com/external/article?articleNumber=321044

Was working as expected in 8.0 U2.  Needing to move to vmware.vmware_rest.appliance_services, but the depreciation should be specifically called out on the appliance_vmon_service component

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware.vmware_rest.appliance_vmon_service

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.6]
  config file = /root/repos/Ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/repos/Ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
vmware.vmware_rest 2.3.1  
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/root/repos/Ansible/ansible.cfg) = ['/root/repos/Ansible/collections']
CONFIG_FILE() = /root/repos/Ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/root/repos/Ansible/ansible.cfg) = ['/root/repos/Ansible/custom_filters']
DEFAULT_ROLES_PATH(/root/repos/Ansible/ansible.cfg) = ['/root/repos/Ansible/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/root/repos/Ansible/ansible.cfg) = ['/root/repos/Ansible/custom_plugins/mitogen-0.3.4/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(/root/repos/Ansible/ansible.cfg) = 40
HOST_KEY_CHECKING(/root/repos/Ansible/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/root/repos/Ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
    - name: Netdumper Service automatic startup
      vmware.vmware_rest.appliance_vmon_service:
        vcenter_hostname: "{{ inventory_hostname }}"
        vcenter_username: "{{ vcenter_user }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vmware_validate_certs }}"
        service: netdumper
        startup_type: AUTOMATIC
      delegate_to: localhost
      register: result
      until: result is not failed
      retries: 2
      delay: 60
```

##### EXPECTED RESULTS

Service is set to startup_type of automatic

##### ACTUAL RESULTS

```paste below
    "type": "com.vmware.vapi.std.errors.service_unavailable",
    "value": {
        "error_type": "SERVICE_UNAVAILABLE",
        "messages": [
            {
                "args": [],
                "default_message": "Service unavailable.",
                "id": "com.vmware.vapi.endpoint.cis.ServiceUnavailable"
            }
        ]
    }
}
```
