### ISSUE TITLE
resize_ex Operation in appliance_system_storage module Does Not Return new_size and old_size for Partition Resizing

### ISSUE THREAD

**Issue by prabinovRedhat** [ansible-collections/vmware.vmware_rest#571]
### Summary

**Bug Description:**
The resize_ex operation in the vmware.vmware_rest.appliance_system_storage module does not return the expected new_size and old_size for the resized partition. The value dictionary in the response is empty, which contradicts the module's documentation.

**Actual Result:**

The response contains an empty dictionary for value:
```
{
  "resize_ex_result": {
    "changed": false,
    "failed": false,
    "value": {}
  }
}
```
**Expected Result:**

The value dictionary should include before and after keys with the states of the partition before and after the resize operation:
```
{
  "resize_ex_result": {
    "changed": true,
    "failed": false,
    "value": {
      "lv_root_0": {
        "new_size": 104312832,
        "old_size": 53985280
      }
    }
  }
} 
```
**Steps to Reproduce:**

Execute the resize_ex operation using the following task:
 
```
- name: Resize the first partition and return the state before and after the operation
  vmware.vmware_rest.appliance_system_storage:
    state: resize_ex
  register: resize_ex_result
```
Observe the returned value in the result.

### Issue Type

Feature Idea

### Component Name

appliance_system_storage 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
