### ISSUE TITLE
vcenter_vm_hardware_boot module failed to change efi_legacy_boot for existing machine

### ISSUE THREAD

**Issue by anna-savina** [ansible-collections/vmware.vmware_rest#585]
### Summary

**Description:**

vmware.vmware_rest.vcenter_vm_hardware_boot module failed to change efi_legacy_boot for existing machine

**Steps to reproduce:**

1. Create a VM
 
```
- name: Create a VM
  vmware.vmware_rest.vcenter_vm:
    placement:
      cluster: "{{ cluster_id }}"
      datastore: "{{ datastore_id }}"
      folder: "{{ folder_id }}"
    name: "{{ test_vm_name }}"
    guest_OS: RHEL_8_64
    hardware_version: VMX_20
    memory:
      hot_add_enabled: true
      size_MiB: 1024
  register: test_vm
```
 
2. Modify efi_legacy_boot parameter

```
- name: Change a VM boot parameters
  vmware.vmware_rest.vcenter_vm_hardware_boot:
    vm: '{{ test_vm.id }}'
    type: EFI
    efi_legacy_boot: true
  register: _result
```

**Expected result:**

efi_legacy_boot is true

**Actual result:**

`FAILED! => {"changed": false, "id": null, "value": {"error_type": "INVALID_ARGUMENT", "messages": [{"args": ["com.vmware.vcenter.vm.hardware.boot.update_spec", "type", "<unset>", "efi_legacy_boot"], "default_message": "Structure com.vmware.vcenter.vm.hardware.boot.update_spec has a union constraint with tag 'type' of value '<unset>', for which the field 'efi_legacy_boot' is not allowed to be set.", "id": "vapi.data.structure.union.extra"}]}}`
 

### Issue Type

Feature Idea

### Component Name

vcenter_vm_hardware_boot

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
