### ISSUE TITLE
vcenter_vm_hardware_serial module doesn't use the label when creating a new port

### ISSUE THREAD

**Issue by anna-savina** [ansible-collections/vmware.vmware_rest#586]
### Summary

**Description:**

vmware.vmware_rest.vcenter_vm_hardware_serial module doesn't use the label when creating a new port

**Steps to reproduce:**

1. Create a VM

```
- name: Create a VM
  vmware.vmware_rest.vcenter_vm:
    placement:
      cluster: "{{ cluster_id }}"
      datastore: "{{ datastore_id }}"
      folder: "{{ folder_id }}"
    name: "{{ test_vm_name }}"
    guest_OS: RHEL_8_64
    hardware_version: VMX_20
    memory:
      hot_add_enabled: true
      size_MiB: 1024
  register: test_vm
```
 
2. Create a new port with label
 
```
- name: Create a new serial port
  vmware.vmware_rest.vcenter_vm_hardware_serial:
    vm: '{{ test_vm.id }}'
    label: "new port"
    allow_guest_control: true
  register: _result
```
 
**Actual result:**

_result.value.label is "Serial port 1"

**Expected result:**

_result.value.label is "new port"

### Issue Type

Feature Idea

### Component Name

vcenter_vm_hardware_serial

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
